/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaInicio;

import RegistroJugadores.ListaJugadores;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
//import RegistroJugadores.RegistroJugadoresNodo;
/**
 * @author w.sullivan-DAVID GUTIERREZ SOLANO
 * @version Calculator 1.2v
 * @create 2016-03-02
 */
public class VentanaInicio extends javax.swing.JFrame {
    //Atributos de la clase VentanaInicio  
    public int turno;   //Variable para conocer el turno actual
    public boolean enLinea=true;
    public boolean jugador1=false;
    public boolean jugador2=false;
//    public String jugador01;    //Juarda los datos de registro del jugador 01
//    public String jugador02;    //Juarda los datos de registro del jugador 02
    public int contadorX;   //Variable para llevar el conteo de las X
    public int contador0;   //Variable para llevar el conteo de las 0
    public JTextField [][] labels;   //Arraglo para guardar la informacion de los arreglos
    ListaJugadores registro=new ListaJugadores();
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setLocationRelativeTo(null);    //Localizar JFrame en el centro
        labels=new JTextField[][]{{jTextField1,jTextField2,jTextField3},
                {jTextField4,jTextField5,jTextField6},{jTextField7,jTextField8,jTextField9}}; //Se almacenan los jTextField
        jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JUEGO EL GATO");
        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(390, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(390, 420));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField1.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 80));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField2.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 80, 80));

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField3.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 80, 80));

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField4.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField4.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 80));

        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField5.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField5.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, 80));

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField6.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField6.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 80, 80));

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField7.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField7.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, 80));

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField8.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField8.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 80, 80));

        jTextField9.setBackground(new java.awt.Color(204, 204, 204));
        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField9.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField9.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/animated-cat-image-0001.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 130));

        jMenu2.setText("Opciones");

        jMenuItem1.setText("Iniciar un Nuevo Juego");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Continuar Juego Anterior");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Revisar Lista de Jugadores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setText("Registro de Jugadores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem4.setText("Ver Estadisticas del Juego");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Ayuda");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias Por Jugar 'El Gato'","Saliendo del Sistema",JOptionPane.INFORMATION_MESSAGE);
        System.exit(0); //Salida del Sistema
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        registroJugadores();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        registro.mostrarLista();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public void procesoComprobar(){
        //Bloque de comparacion de jugador01 1 en "X"
        for(int i=0;i<3;i++){
            if(jTextField1.getText().equals("X")){     
                if(jTextField2.getText().equals("X")){
                    if(jTextField3.getText().equals("X")){
                        jugador1=true;
                        jugador2=false;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                    }
                }
            }
            if(jTextField1.getText().equals("X")){     
                    if(jTextField5.getText().equals("X")){
                        if(jTextField9.getText().equals("X")){
                            jugador1=true;
                            jugador2=false;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                        }
                    }
            }
            if(jTextField1.getText().equals("X")){     
                    if(jTextField4.getText().equals("X")){
                        if(jTextField7.getText().equals("X")){
                            jugador1=true;
                            jugador2=false;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                        }
                    }
            }
            //Bloque de comparacion de boton 2
            if(jTextField2.getText().equals("X")){     
                    if(jTextField5.getText().equals("X")){
                        if(jTextField8.getText().equals("X")){
                            jugador1=true;
                            jugador2=false;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                        }
                    }
            }
            //Bloque de comparacion de boton 3
            if(jTextField3.getText().equals("X")){     
                    if(jTextField5.getText().equals("X")){
                        if(jTextField7.getText().equals("X")){
                            jugador1=true;
                            jugador2=false;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                        }
                    }
            }
            if(jTextField3.getText().equals("X")){     
                    if(jTextField6.getText().equals("X")){
                        if(jTextField9.getText().equals("X")){
                            jugador1=true;
                            jugador2=false;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                        }
                    }
            }
            //Bloque de comparacion de boton 4
            if(jTextField4.getText().equals("X")){     
                    if(jTextField5.getText().equals("X")){
                        if(jTextField6.getText().equals("X")){
                            jugador1=true;
                            jugador2=false;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                        }
                    }
            }
            //Bloque de comparacion de boton 7
            if(jTextField7.getText().equals("X")){     
                    if(jTextField8.getText().equals("X")){
                        if(jTextField9.getText().equals("X")){
                            jugador1=true;
                            jugador2=false;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                        }
                    }
            }
            //Bloque de comparacion de jugador02 1 en "O"
            if(jTextField1.getText().equals("O")){     
                if(jTextField2.getText().equals("O")){
                    if(jTextField3.getText().equals("O")){
                        jugador1=false;
                        jugador2=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                    }
                }
            }
            if(jTextField1.getText().equals("O")){     
                    if(jTextField5.getText().equals("O")){
                        if(jTextField9.getText().equals("O")){
                            jugador1=false;
                            jugador2=true;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                        }
                    }
            }
            if(jTextField1.getText().equals("O")){     
                    if(jTextField4.getText().equals("O")){
                        if(jTextField7.getText().equals("O")){
                            jugador1=false;
                            jugador2=true;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                        }
                    }
            }
            
            if(jTextField2.getText().equals("O")){     
                    if(jTextField5.getText().equals("O")){
                        if(jTextField8.getText().equals("O")){
                            jugador1=false;
                            jugador2=true;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                        }
                    }
            }
            
            if(jTextField3.getText().equals("O")){     
                    if(jTextField5.getText().equals("O")){
                        if(jTextField7.getText().equals("O")){
                            jugador1=false;
                            jugador2=true;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                        }
                    }
            }
            if(jTextField3.getText().equals("O")){     
                    if(jTextField6.getText().equals("O")){
                        if(jTextField9.getText().equals("O")){
                            jugador1=false;
                            jugador2=true;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                        }
                    }
            }
            
            if(jTextField4.getText().equals("O")){     
                    if(jTextField5.getText().equals("O")){
                        if(jTextField6.getText().equals("O")){
                            jugador1=false;
                            jugador2=true;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                        }
                    }
            }
            //Bloque de comparacion de boton 7
            if(jTextField7.getText().equals("O")){     
                    if(jTextField8.getText().equals("O")){
                        if(jTextField9.getText().equals("O")){
                            jugador1=false;
                            jugador2=true;
                            JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                        }
                    }
            }
        }    
    }
    
    public void llenarJTextFiel(){
        
    }
    
    /**
     * Metodo para registrar los jugadores
     */
    public void registroJugadores(){  
        String auxiliarNombre1;
        String auxiliarNombre2;
        auxiliarNombre1=JOptionPane.showInputDialog(null,"Ingrese el nombre del Jugador 1: ","Registro del Jugadores",JOptionPane.INFORMATION_MESSAGE);
        auxiliarNombre2=JOptionPane.showInputDialog(null,"Ingrese el nombre del Jugador 2: ","Registro del Jugadores",JOptionPane.INFORMATION_MESSAGE);
        if((!"".equals(auxiliarNombre1))&&(!"".equals(auxiliarNombre2))){
            registro.insertar(auxiliarNombre1);
            registro.insertar(auxiliarNombre2);
        }else{
            JOptionPane.showMessageDialog(null,"Error, no se han guardado correctamente los datos"+"\n\nJugador 1: "+auxiliarNombre1+"\nJugador 2: "+auxiliarNombre2,"Error del Sistema",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
