/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaInicio;

import RegistroJugadores.ListaJugadores;    //Importacion del paquete RegistroJugadores y la clase ListaJugadores
import java.awt.Color;      //Importacion de la libreria de color para usar en el JFrame
import java.util.Random;    //Libreria Random para utilizar en el sorteo
import javax.swing.JButton; //Libreria para los botones
import javax.swing.JOptionPane; //Libreria del JOptionPane para impresiones
import RegistroJugadores.RegistroJugadoresNodo;
/**
 * @author w.sullivan-DAVID GUTIERREZ SOLANO
 * @version Calculator 1.2v
 * @create 2016-03-02
 */
public class VentanaInicio extends javax.swing.JFrame {
    //Atributos de la clase VentanaInicio  
    public boolean ganador;   //Variable para conocer si hay ganador  
    public boolean jugador1;    //Variable para el turno del jugador 1
    public boolean jugador2;    //Variable para el turno del jugador 2
    public boolean bloqueo;     //Variable para bloqueo abilitar sentencias en los botones
    public String auxiliarNombre1; //Variable para datos del jugador 1
    public String auxiliarNombre2; //Variable para datos del jugador 2
    public JButton [][] botones;   //Arraglo para guardar la informacion de los botones
    int count;  //Contador general de inscripciones
    ListaJugadores registro=new ListaJugadores();   //Creacion del Objeto tipo ListaJugadores
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {        
        initComponents();   //Inicio del proceso general del JFrame
        this.getContentPane().setBackground(Color.lightGray);   //Se establece el color de fondo del JFrame
        setLocationRelativeTo(null);    //Localizar JFrame en el centro
        botones=new JButton[][]{{jButton3,jButton1,jButton2},   
                {jButton6,jButton4,jButton5},{jButton9,jButton7,jButton8}}; //Se declaran los indices del Arreglo con los JButton      
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btn_Sorteo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JUEGO EL GATO");
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(345, 485));
        setMinimumSize(new java.awt.Dimension(345, 485));
        setPreferredSize(new java.awt.Dimension(345, 485));
        setResizable(false);
        setSize(new java.awt.Dimension(345, 485));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/animated-cat-image-0001.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 140));

        jButton1.setBackground(new java.awt.Color(87, 227, 218));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton1.setForeground(java.awt.Color.black);
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 90));

        jButton2.setBackground(new java.awt.Color(87, 227, 218));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton2.setForeground(java.awt.Color.black);
        jButton2.setAutoscrolls(true);
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, 90));

        jButton3.setBackground(new java.awt.Color(87, 227, 218));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton3.setForeground(java.awt.Color.black);
        jButton3.setAutoscrolls(true);
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 100, 90));

        jButton4.setBackground(new java.awt.Color(87, 227, 218));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton4.setForeground(java.awt.Color.black);
        jButton4.setAutoscrolls(true);
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 90));

        jButton5.setBackground(new java.awt.Color(87, 227, 218));
        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton5.setForeground(java.awt.Color.black);
        jButton5.setAutoscrolls(true);
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, 90));

        jButton6.setBackground(new java.awt.Color(87, 227, 218));
        jButton6.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton6.setForeground(java.awt.Color.black);
        jButton6.setAutoscrolls(true);
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 100, 90));

        jButton7.setBackground(new java.awt.Color(87, 227, 218));
        jButton7.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton7.setForeground(java.awt.Color.black);
        jButton7.setAutoscrolls(true);
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 90));

        jButton8.setBackground(new java.awt.Color(87, 227, 218));
        jButton8.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton8.setForeground(java.awt.Color.black);
        jButton8.setAutoscrolls(true);
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, 90));

        jButton9.setBackground(new java.awt.Color(87, 227, 218));
        jButton9.setFont(new java.awt.Font("Ubuntu", 1, 26)); // NOI18N
        jButton9.setForeground(java.awt.Color.black);
        jButton9.setAutoscrolls(true);
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 100, 90));

        btn_Sorteo.setBackground(new java.awt.Color(224, 207, 207));
        btn_Sorteo.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btn_Sorteo.setText("Sorteo");
        btn_Sorteo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Sorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SorteoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sorteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 80, 30));

        jMenu2.setText("Opciones");

        jMenuItem1.setText("Iniciar un Nuevo Juego");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Continuar Juego Anterior");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Revisar Lista de Jugadores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setText("Registro de Jugadores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem4.setText("Ver Estadisticas del Juego");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Ayuda");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metodo vacio
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed
    //Btoton para salir del sistema completamente
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias Por Jugar 'El Gato'","Saliendo del Sistema",JOptionPane.INFORMATION_MESSAGE);  //Impresion de mensaje de salida del sistema
        System.exit(0); //Orden de Salida del Sistema
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    //Boton para el registro de los jugadores
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        registroJugadores();    //Llamada del metodo de registroJugadores
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    //Boton de inicio de nuevo Juego
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //Boton para continuar un juego juardado
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    //Boton para ver el historial de jugadores inscritos
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        registro.mostrarLista();    //Ver la lista de jugadores que han jugado
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    //Boton para ver las estadisticas de los jugadores
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
            //Solicitud de datos de estadisticas de los jugadores
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    //Bonton numero 3 del panel de juego
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton3.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton3.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton3.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }   
    }//GEN-LAST:event_jButton3ActionPerformed
    //Bonton numero 1 del panel de juego
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton1.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton1.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton1.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }  
    }//GEN-LAST:event_jButton1ActionPerformed
    //Bonton numero 2 del panel de juego
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton2.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton2.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton2.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }  
    }//GEN-LAST:event_jButton2ActionPerformed
    //Bonton numero 6 del panel de juego
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton6.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton6.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton6.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }  
    }//GEN-LAST:event_jButton6ActionPerformed
    //Bonton numero 4 del panel de juego
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton4.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton4.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton4.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }  
    }//GEN-LAST:event_jButton4ActionPerformed
    //Bonton numero 5 del panel de juego
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton5.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton5.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton5.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }  
    }//GEN-LAST:event_jButton5ActionPerformed
    //Bonton numero 9 del panel de juego
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton9.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton9.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton9.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }  
    }//GEN-LAST:event_jButton9ActionPerformed
    //Bonton numero 7 del panel de juego
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton7.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton7.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton7.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }  
    }//GEN-LAST:event_jButton7ActionPerformed
    //Bonton numero 8 del panel de juego
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       if(bloqueo==true){  //Validacion si hay turno
            if(jugador1==true){ //Condicion del jugador 1
            jButton8.setText("X");
            jugador1=false;
            jugador2=true;
        }else{  //Condicion del jugador 2
            jButton8.setText("O");
            jugador1=true;
            jugador2=false;
        }
        jButton8.setEnabled(false);
        comprobarCaracter();    //Comprobacion de datos
        } else {    //Sentencia si no hay turno
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se ha sorteado el turno".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }  
    }//GEN-LAST:event_jButton8ActionPerformed
    //Bonton para el sorteo del jugador que inicia el juego
    private void btn_SorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SorteoActionPerformed
        // TODO add your handling code here:
        if((auxiliarNombre1!=null)&&(auxiliarNombre2!=null)){
            Random auxiliar = new Random(); //Objeto Random
            int mayor=auxiliar.nextInt(10)+1;   //Calculo de numero aleatorio
            if(mayor>=5){  //Condicion
                jugador1=true;  //Asignar valor a jugador 1
                jugador2=false; //Asignar valor a jugador 2
            }else{
                jugador2=true;  //Asignar valor a jugador 1
                jugador1=false; //Asignar valor a jugador 2
            }
            btn_Sorteo.setEnabled(false); //Se desactiva el boton de sorteo
            bloqueo=true;
        }else{
            JOptionPane.showMessageDialog(null, "lo sentimos aun no se han registrado jugadores".toUpperCase(),"Error del sistema",JOptionPane.ERROR_MESSAGE); //Error del sistema donde no hay turno aun
        }
        
    }//GEN-LAST:event_btn_SorteoActionPerformed

    /**
     * Metodo que valida las opciones del juego durante el proceso del juego
     */
    public void comprobarCaracter(){
        //Creacion de todas las sentecias para la validacion de las opciones del ganador
        //Validacion de botones 1,2,3
        if(jButton1.getText().equals("X")){     
            if(jButton2.getText().equals("X")){
                if(jButton3.getText().equals("X")){
                    ganador=true;
                    JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre1,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        //Validacion de botones 1,5,9
        if(jButton1.getText().equals("X")){     
            if(jButton5.getText().equals("X")){
                if(jButton9.getText().equals("X")){
                    ganador=true;
                    JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre1,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 1,4,7
        if(jButton1.getText().equals("X")){     
                if(jButton4.getText().equals("X")){
                    if(jButton7.getText().equals("X")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre1,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 2,5,8
        if(jButton2.getText().equals("X")){     
                if(jButton5.getText().equals("X")){
                    if(jButton8.getText().equals("X")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre1,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 3,5,7
        if(jButton3.getText().equals("X")){     
                if(jButton5.getText().equals("X")){
                    if(jButton7.getText().equals("X")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre1,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 3,6,9
        if(jButton3.getText().equals("X")){     
                if(jButton6.getText().equals("X")){
                    if(jButton9.getText().equals("X")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre1,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 4,5,6
        if(jButton4.getText().equals("X")){     
                if(jButton5.getText().equals("X")){
                    if(jButton6.getText().equals("X")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre1,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 7,8,9
        if(jButton7.getText().equals("X")){     
                if(jButton8.getText().equals("X")){
                    if(jButton9.getText().equals("X")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre1,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 1,2,3
        if(jButton1.getText().equals("O")){     
            if(jButton2.getText().equals("O")){
                if(jButton3.getText().equals("O")){
                    ganador=true;
                    JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre2,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        //Validacion de botones 1,5,9
        if(jButton1.getText().equals("O")){     
                if(jButton5.getText().equals("O")){
                    if(jButton9.getText().equals("O")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre2,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 1,4,7
        if(jButton1.getText().equals("O")){     
                if(jButton4.getText().equals("O")){
                    if(jButton7.getText().equals("O")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre2,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 2,5,8
        if(jButton2.getText().equals("O")){     
                if(jButton5.getText().equals("O")){
                    if(jButton8.getText().equals("O")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre2,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 3,5,7
        if(jButton3.getText().equals("0")){     
                if(jButton5.getText().equals("0")){
                    if(jButton7.getText().equals("0")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre2,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 3,6,9
        if(jButton3.getText().equals("0")){     
                if(jButton6.getText().equals("0")){
                    if(jButton9.getText().equals("0")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre2,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 4,5,6
        if(jButton4.getText().equals("0")){     
                if(jButton5.getText().equals("0")){
                    if(jButton6.getText().equals("0")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre2,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
        //Validacion de botones 7,8,9
        if(jButton7.getText().equals("0")){     
                if(jButton8.getText().equals("0")){
                    if(jButton9.getText().equals("0")){
                        ganador=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+auxiliarNombre2,"GANADOR",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
        }
//        if(ganador==false){
//            JOptionPane.showMessageDialog(null,"Lo sentimos el juego ha sido empate".toUpperCase(),"JUEGO EMPATE",JOptionPane.INFORMATION_MESSAGE);
//        }
    }
    
    /**
     * Metodo para registrar los jugadores del Juego
     */
    public void registroJugadores(){  
        //Solicitud de los datos
        auxiliarNombre1=JOptionPane.showInputDialog(null,"Ingrese el nombre del Jugador 1 ","Registro del Jugadores",JOptionPane.INFORMATION_MESSAGE); //Solicitud de registro del jugador 1
        auxiliarNombre2=JOptionPane.showInputDialog(null,"Ingrese el nombre del Jugador 2 ","Registro del Jugadores",JOptionPane.INFORMATION_MESSAGE); //Solicitud de registro del jugador 2
        if((!"".equals(auxiliarNombre1))&&(!"".equals(auxiliarNombre2))){   //Validacion del registro de jugadores en el sistema
            count++;    //Contador
            registro.insertar(count,auxiliarNombre1);   //Inscripcion el jugador 1
            count++;    //Contador
            registro.insertar(count,auxiliarNombre2);   //Inscripcion el jugador 1                     
            
        }else{
            JOptionPane.showMessageDialog(null,"Error, no se han guardado correctamente los datos"+"\n\nJugador 1: "+auxiliarNombre1+"\nJugador 2: "+auxiliarNombre2,"Error del Sistema",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sorteo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
