/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyectogato;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*; //Se importa toda la libreria swing
/**
 * @author w.sullivan-DAVID GUTIERREZ SOLANO
 * @version Calculator 1.2v
 * @create 2016-03-02
 */
public class WindowStar extends javax.swing.JFrame {
    //Creating Attributes for Class WindowStar
    public int turno;   //Variable para conocer el turno actual
    public boolean enLinea=true;
    public boolean jugador1=false;
    public boolean jugador2=false;
    public String jugador01;
    public String jugador02;
    public int contadorX;   //Variable para llevar el conteo de las X
    public int contador0;   //Variable para llevar el conteo de las 0
    public JButton [][] botones;   //Arraglo para guardar la informacion de los arreglos
   
    /**
     * Creates new form WindowStar
     */
    public WindowStar() {
        initComponents();   //Inicia totos los componentes de la clase
        setLocationRelativeTo(null);    //Localizar JFrame en el centro
        botones=new JButton[][]{{jButton1,jButton2,jButton3},
                {jButton4,jButton5,jButton6},{jButton7,jButton8,jButton9}}; //Se almacenan los jButton
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Gato");
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton6.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton7.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton8.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jButton9.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem5.setText("Guardar Partida");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Registro de Jugador");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");

        jMenuItem1.setText("Iniciar un Nuevo Juego");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Continuar Juego Anterior");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Revisar Lista de Jugadores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias Por Jugar 'El Gato'","Saliendo del Sistema",JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    //JButton 1
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setText("");
        jButton1.addActionListener(new ActionListener() {
            @Override   //Sobreecibre el metodo
            public void actionPerformed(ActionEvent e) {    //Metodo Override para sobreecibir la informacon del boton
                jButton1ActionPerformed(e);     //Captura la accion del boton y devuelve
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed
    //JButton 2
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setText("");
        jButton2.addActionListener(new ActionListener() {
            @Override   //Sobreecibre el metodo
            public void actionPerformed(ActionEvent e) {    //Metodo Override para sobreecibir la informacon del boton
                jButton2ActionPerformed(e);     //Captura la accion del boton y devuelve
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed
    //JButton 3
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setText("");
        jButton3.addActionListener(this::jButton3ActionPerformed //Sobreecibre el metodo
        //Metodo Override para sobreecibir la informacon del boton
        //Captura la accion del boton y devuelve
        );
    }//GEN-LAST:event_jButton3ActionPerformed
    //JButton 4
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setText("");
        jButton4.addActionListener(this::jButton4ActionPerformed //Sobreecibre el metodo
        //Metodo Override para sobreecibir la informacon del boton
        //Captura la accion del boton y devuelve
        );
    }//GEN-LAST:event_jButton4ActionPerformed
    //JButton 5
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jButton5.setText("");
        jButton5.addActionListener(this::jButton5ActionPerformed //Sobreecibre el metodo
        //Metodo Override para sobreecibir la informacon del boton
        //Captura la accion del boton y devuelve
        );
    }//GEN-LAST:event_jButton5ActionPerformed
    //JButton 6
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton6.setText("");
        jButton6.addActionListener(this::jButton6ActionPerformed //Sobreecibre el metodo
        //Metodo Override para sobreecibir la informacon del boton
        //Captura la accion del boton y devuelve
        );
    }//GEN-LAST:event_jButton6ActionPerformed
    //JButton 7
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setText("");
        jButton7.addActionListener(this::jButton7ActionPerformed //Sobreecibre el metodo
        //Metodo Override para sobreecibir la informacon del boton
        //Captura la accion del boton y devuelve
        );
    }//GEN-LAST:event_jButton7ActionPerformed
    //JButton 8
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton8.setText("");
        jButton8.addActionListener(this::jButton8ActionPerformed //Sobreecibre el metodo
        //Metodo Override para sobreecibir la informacon del boton
        //Captura la accion del boton y devuelve
        );
    }//GEN-LAST:event_jButton8ActionPerformed
    //JButton 9
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jButton9.setText("");
        jButton9.addActionListener(this::jButton9ActionPerformed );//Sobreecibre el metodo
        //Metodo Override para sobreecibir la informacon del boton
        //Captura la accion del boton y devuelve
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        RegistroJugador instanciaRegistroJugador=new RegistroJugador(this,true);
        instanciaRegistroJugador.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,toString(),"Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    @Override
    public String toString() {
        return "JUGADOR 1: " + this.getJugador01() + "\nJUGADOR 2: " + this.getJugador02() ;
    }
    
    public void procesoComprobar(){
        //Bloque de comparacion de jugador01 1 en "X"
        if(jButton1.getText().equals("X")){     
            if(jButton2.getText().equals("X")){
                if(jButton3.getText().equals("X")){
                    jugador1=true;
                    jugador2=false;
                    JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                }
            }
        }
        if(jButton1.getText().equals("X")){     
                if(jButton5.getText().equals("X")){
                    if(jButton9.getText().equals("X")){
                        jugador1=true;
                        jugador2=false;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                    }
                }
        }
        if(jButton1.getText().equals("X")){     
                if(jButton4.getText().equals("X")){
                    if(jButton7.getText().equals("X")){
                        jugador1=true;
                        jugador2=false;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                    }
                }
        }
        //Bloque de comparacion de boton 2
        if(jButton2.getText().equals("X")){     
                if(jButton5.getText().equals("X")){
                    if(jButton8.getText().equals("X")){
                        jugador1=true;
                        jugador2=false;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                    }
                }
        }
        //Bloque de comparacion de boton 3
        if(jButton3.getText().equals("X")){     
                if(jButton5.getText().equals("X")){
                    if(jButton7.getText().equals("X")){
                        jugador1=true;
                        jugador2=false;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                    }
                }
        }
        if(jButton3.getText().equals("X")){     
                if(jButton6.getText().equals("X")){
                    if(jButton9.getText().equals("X")){
                        jugador1=true;
                        jugador2=false;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                    }
                }
        }
        //Bloque de comparacion de boton 4
        if(jButton4.getText().equals("X")){     
                if(jButton5.getText().equals("X")){
                    if(jButton6.getText().equals("X")){
                        jugador1=true;
                        jugador2=false;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                    }
                }
        }
        //Bloque de comparacion de boton 7
        if(jButton7.getText().equals("X")){     
                if(jButton8.getText().equals("X")){
                    if(jButton9.getText().equals("X")){
                        jugador1=true;
                        jugador2=false;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador01);
                    }
                }
        }
        //Bloque de comparacion de jugador02 1 en "O"
        if(jButton1.getText().equals("O")){     
            if(jButton2.getText().equals("O")){
                if(jButton3.getText().equals("O")){
                    jugador1=false;
                    jugador2=true;
                    JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                }
            }
        }
        if(jButton1.getText().equals("O")){     
                if(jButton5.getText().equals("O")){
                    if(jButton9.getText().equals("O")){
                        jugador1=false;
                        jugador2=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                    }
                }
        }
        if(jButton1.getText().equals("O")){     
                if(jButton4.getText().equals("O")){
                    if(jButton7.getText().equals("O")){
                        jugador1=false;
                        jugador2=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                    }
                }
        }
        //Bloque de comparacion de boton 2
        if(jButton2.getText().equals("O")){     
                if(jButton5.getText().equals("O")){
                    if(jButton8.getText().equals("O")){
                        jugador1=false;
                        jugador2=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                    }
                }
        }
        //Bloque de comparacion de boton 3
        if(jButton3.getText().equals("O")){     
                if(jButton5.getText().equals("O")){
                    if(jButton7.getText().equals("O")){
                        jugador1=false;
                        jugador2=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                    }
                }
        }
        if(jButton3.getText().equals("O")){     
                if(jButton6.getText().equals("O")){
                    if(jButton9.getText().equals("O")){
                        jugador1=false;
                        jugador2=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                    }
                }
        }
        //Bloque de comparacion de boton 4
        if(jButton4.getText().equals("O")){     
                if(jButton5.getText().equals("O")){
                    if(jButton6.getText().equals("O")){
                        jugador1=false;
                        jugador2=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                    }
                }
        }
        //Bloque de comparacion de boton 7
        if(jButton7.getText().equals("O")){     
                if(jButton8.getText().equals("O")){
                    if(jButton9.getText().equals("O")){
                        jugador1=false;
                        jugador2=true;
                        JOptionPane.showMessageDialog(null,"felicidades ganaste la partida ".toUpperCase()+jugador02);
                    }
                }
        }
    }
    
    public WindowStar(String jugador01,String jugador02){
        this.jugador01=jugador01;
        this.jugador01=jugador02;
    }
    public void setJugador01(String jugador){
        this.jugador01=jugador;
    }
    
    public void setJugador02(String jugador){
        this.jugador02=jugador;
    }
    public String getJugador01(){return jugador01;}
    
    public String getJugador02(){return jugador02;}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowStar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowStar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowStar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowStar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowStar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables

   
}
